name: CD - test-app

on:
  workflow_dispatch:
    inputs:
      deployment_targets:
        description: 'Deployment target'
        required: true
        type: choice
        options:
          - backend-server

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: test-backend
  ENV_FILE_PATH: /home/ec2-user/projects/.env
  DOCKER_TAG: latest
  ECR_REGISTRY: 776410619441.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  deploy-multiple-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_REGION,ECR_REPOSITORY,ENV_FILE_PATH,DOCKER_TAG,ECR_REGISTRY
          script: |
            set -e

            echo "Preparing folders"
            mkdir -p /home/ec2-user/projects/logs/

            echo "Logging into ECR"
            aws ecr get-login-password --region "$AWS_REGION" | \
              docker login --username AWS --password-stdin "$ECR_REGISTRY"

            echo "Pulling Docker image"
            docker pull "$ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG"

            container_name="test-app"
            port=8003
            internal_port=3000

            echo "Deploying $container_name on port $port"

            if docker ps -a --format '{{.Names}}' | grep -wq "$container_name"; then
              echo "Removing existing container $container_name"
              docker rm -f "$container_name"
            fi

            docker run -d \
              --restart unless-stopped \
              -p "$port:$internal_port" \
              -v /home/ec2-user/projects/logs/:/app/logs/ \
              --name "$container_name" \
              --env-file "$ENV_FILE_PATH" \
              "$ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG"

            echo "Cleaning up old images"
            docker image prune -f